# netlify.toml
[build]
  base    = "frontend"     # folder project kamu
  command = "npm run build"
  publish = "frontend/dist" # hasil build otomatis masuk sini

[build.environment]
  NODE_VERSION = "20"       # lebih stabil buat Vite + React
